# ============================================================
# Figure 3 CNV plasticity compact panels
# ============================================================
#
# GitHub script name : 02_plot_cnv_plasticity_compact_panels.R
# Original file      : Fig.3.CNV.plasticity.R
# Manuscript context : Wilms tumor developmental plasticity project
#
# Purpose:
#   Generates compact CNV panels summarizing chromosome-arm CNV profiles and cell-level CNV burden across malignant subcompartments.
#
# Usage:
#   Run from the root of the GitHub repository, or edit the input/output
#   paths in the SETTINGS / Input-output section below before running.
#
# Notes for reproducibility:
#   - This script preserves the analytical logic of the original working
#     manuscript script.
#   - Hard-coded local paths from the original analysis may need to be
#     changed to repository-relative paths such as data/processed/ and
#     results/figure_XX/.
#   - Large objects such as Seurat .RData files should usually be stored
#     outside GitHub or tracked with Git LFS / external data release.
#
# Suggested output folder:
#   results/figure_03/
#
# ============================================================

# ============================================================
# Manuscript compact CNV figure:
# Panel E left + Panel C right, all samples stacked vertically
# Uses outputs already generated by the existing Wilms CNV script
# ============================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(readr)
  library(tidyr)
  library(stringr)
  library(tibble)
  library(ggplot2)
  library(ggpubr)
  library(patchwork)
  library(cowplot)
})

# ============================================================
# 1. INPUTS
# ============================================================

outdir <- "~/Documents/Izar_Group/wilms/wilms_CNV_panels_with_statistics"

avg_cnv_file <- file.path(outdir, "ALL_samples_average_CNV_by_state_arm.tsv")
arm_stats_file <- file.path(outdir, "ALL_samples_samplewise_arm_level_stats.tsv")
meta_file <- file.path(outdir, "ALL_samples_cell_level_CNV_metadata.tsv")
pairwise_file <- file.path(outdir, "ALL_samples_pairwise_CNV_burden_stats.tsv")

fig_outdir <- file.path(outdir, "manuscript_compact_panelE_panelC")
dir.create(fig_outdir, showWarnings = FALSE, recursive = TRUE)

outfile_pdf <- file.path(
  fig_outdir,
 # "Wilms_all_samples_compact_PanelE_left_PanelC_right.pdf"
  "Wilms_UNTREATED_compact_PanelE_left_PanelC_right.pdf"
)

outfile_png <- file.path(
  fig_outdir,
 # "Wilms_all_samples_compact_PanelE_left_PanelC_right.png"
  "Wilms_UNTREATED_compact_PanelE_left_PanelC_right.png"
)

keep_subcompartments <- c("blastema", "epithelium", "stroma")

subcompartment_colors <- c(
  "blastema"   = "#E64B35",
  "stroma"     = "#4DBBD5",
  "epithelium" = "#00A087"
)

# Same CNV scale as the original script
cnv_limits <- c(-2, 2)

cnv_colors <- c(
  "#313695",
           "#74add1",
           "#f7f7f7",
           "#f46d43",
           "#a50026"
)

# ============================================================
# 2. LOAD DATA
# ============================================================

avg_cnv <- read_tsv(avg_cnv_file, show_col_types = FALSE)
arm_stats <- read_tsv(arm_stats_file, show_col_types = FALSE)
meta <- read_tsv(meta_file, show_col_types = FALSE)
pairwise_stats <- read_tsv(pairwise_file, show_col_types = FALSE)

avg_cnv <- avg_cnv %>%
  mutate(
    sample = as.character(sample),
    subcompartment = factor(subcompartment, levels = keep_subcompartments)
  )

arm_stats <- arm_stats %>%
  mutate(
    sample = as.character(sample),
    chrom_arm = as.character(chrom_arm)
  )

meta <- meta %>%
  mutate(
    sample = as.character(sample),
    subcompartment = factor(subcompartment, levels = keep_subcompartments)
  )

pairwise_stats <- pairwise_stats %>%
  mutate(sample = as.character(sample))

# ============================================================
# 3. CHROMOSOME ARM ORDER
# ============================================================

arm_levels <- c(rbind(paste0(1:22, "p"), paste0(1:22, "q")))
arm_levels <- c(arm_levels, "Xp", "Xq", "Yp", "Yq")

avg_cnv <- avg_cnv %>%
  mutate(chrom_arm = factor(chrom_arm, levels = arm_levels, ordered = TRUE))

arm_stats <- arm_stats %>%
  mutate(chrom_arm = factor(chrom_arm, levels = arm_levels, ordered = TRUE))

# samples_use <- intersect(
#   unique(avg_cnv$sample),
#   unique(meta$sample)
# )
# 
# samples_use <- sort(samples_use)

# ============================================================
# UNTREATED SAMPLES ONLY
# ============================================================

samples_use <- c(
  "W612",
  "W340",
  "W011",
  "W132",
  "W495",
  "W008",
  "W007",
  "W005",
  "W004",
  "W241",
  "W040",
  "W012"
)

# keep only samples present in data
samples_use <- samples_use[
  samples_use %in% unique(avg_cnv$sample) &
    samples_use %in% unique(meta$sample)
]

# ============================================================
# 4. HELPER: PANEL E FOR ONE SAMPLE
# ============================================================

make_panel_E <- function(sample_id) {
  
  df <- avg_cnv %>%
    filter(sample == sample_id) %>%
    mutate(
      subcompartment = factor(subcompartment, levels = keep_subcompartments),
      chrom_arm = factor(chrom_arm, levels = arm_levels, ordered = TRUE)
    )
  
  sig_df <- arm_stats %>%
    filter(sample == sample_id) %>%
    mutate(
      chrom_arm = factor(chrom_arm, levels = arm_levels, ordered = TRUE),
      signif_clean = case_when(
        is.na(signif) ~ "",
        signif == "ns" ~ "",
        TRUE ~ signif
      )
    ) %>%
    filter(signif_clean != "")
  
  p <- ggplot(df, aes(x = chrom_arm, y = subcompartment, fill = mean_cnv)) +
    geom_tile(color = "black", linewidth = 0.15) +
    geom_text(
      data = sig_df,
      aes(
        x = chrom_arm,
        y = keep_subcompartments[1],
        label = signif_clean
      ),
      inherit.aes = FALSE,
      size = 2.2,
      fontface = "bold",
      vjust = -0.15
    ) +
    scale_fill_gradientn(
      colors = cnv_colors,
      limits = cnv_limits,
      oob = scales::squish,
      name = "Mean CNV",
      breaks = c(-2, -1, 0, 1, 2),
      labels = c("bdel", "del", "neu", "amp", "bamp")
    ) +
    scale_y_discrete(drop = FALSE) +
    scale_x_discrete(drop = FALSE) +
    labs(
      title = sample_id,
      x = NULL,
      y = NULL
    ) +
    theme_bw(base_size = 8) +
    theme(
      plot.title = element_text(
        size = 9,
        face = "bold",
        hjust = 0,
        margin = margin(b = 2)
      ),
      axis.text.x = element_text(
        size = 5,
        angle = 90,
        vjust = 0.5,
        hjust = 1
      ),
      axis.text.y = element_text(size = 7),
      axis.ticks = element_blank(),
      panel.grid = element_blank(),
      legend.position = "right",
      legend.title = element_text(size = 7),
      legend.text = element_text(size = 6),
      plot.margin = margin(2, 4, 2, 2)
    )
  
  return(p)
}

# ============================================================
# 5. HELPER: PANEL C FOR ONE SAMPLE
# ============================================================

make_panel_C <- function(sample_id) {
  
  df <- meta %>%
    filter(sample == sample_id) %>%
    filter(
      !is.na(cnv_burden_main),
      !is.na(subcompartment)
    ) %>%
    mutate(
      subcompartment = factor(subcompartment, levels = keep_subcompartments)
    )
  
  kw <- tryCatch({
    kruskal.test(cnv_burden_main ~ subcompartment, data = df)
  }, error = function(e) NULL)
  
  kw_label <- if (!is.null(kw)) {
    paste0("KW P = ", signif(kw$p.value, 3))
  } else {
    "KW P = NA"
  }
  
  comparisons_use <- list(
    c("blastema", "epithelium"),
    c("blastema", "stroma"),
    c("epithelium", "stroma")
  )
  
  p <- ggplot(df, aes(x = subcompartment, y = cnv_burden_main)) +
    geom_violin(
      aes(fill = subcompartment),
      color = "black",
      trim = FALSE,
      linewidth = 0.25,
      alpha = 0.8
    ) +
    geom_boxplot(
      width = 0.14,
      outlier.shape = NA,
      fill = "white",
      color = "black",
      linewidth = 0.25
    ) +
    # geom_jitter(
    #   width = 0.10,
    #   size = 0.25,
    #   alpha = 0.20
    # ) +
    scale_fill_manual(values = subcompartment_colors, drop = FALSE) +
    labs(
      title = kw_label,
      x = NULL,
      y = "CNV burden"
    ) +
    theme_bw(base_size = 8) +
    theme(
      plot.title = element_text(size = 8, face = "bold", hjust = 0.5),
      axis.text.x = element_text(
        size = 6,
        angle = 30,
        hjust = 1
      ),
      axis.text.y = element_text(size = 6),
      axis.title.y = element_text(size = 7),
      legend.position = "none",
      panel.grid = element_blank(),
      plot.margin = margin(2, 2, 2, 4)
    )
  
  if (length(unique(df$subcompartment)) >= 2) {
    p <- p +
      stat_compare_means(
        comparisons = comparisons_use,
        method = "wilcox.test",
        label = "p.format",
        hide.ns = FALSE,
        size = 2.0,
        tip.length = 0.01
      )
  }
  
  return(p)
}

# ============================================================
# 6. BUILD ONE ROW PER SAMPLE
# ============================================================

sample_rows <- lapply(samples_use, function(sid) {
  
  pE <- make_panel_E(sid)
  pC <- make_panel_C(sid)
  
  pE + pC +
    plot_layout(
      widths = c(3.4, 1.15),
      guides = "collect"
    ) &
    theme(
      legend.position = "right"
    )
})

# ============================================================
# 7. COMBINE ALL SAMPLES
# ============================================================

final_plot <- wrap_plots(
  sample_rows,
  ncol = 1
) +
  plot_annotation(
    title = "Sample-resolved CNV architecture and CNV burden across Wilms tumor subcompartments",
    subtitle = "Left: average chromosome-arm CNV state by subcompartment. Right: cell-level CNV burden with sample-wise statistics.",
    theme = theme(
      plot.title = element_text(size = 13, face = "bold"),
      plot.subtitle = element_text(size = 9)
    )
  )

# ============================================================
# 8. SAVE
# ============================================================

n_samples <- length(samples_use)

pdf_height <- max(6, n_samples * 1.45)
pdf_width <- 15

ggsave(
  filename = outfile_pdf,
  plot = final_plot,
  width = pdf_width,
  height = pdf_height,
  units = "in",
  device = "pdf"
)

ggsave(
  filename = outfile_png,
  plot = final_plot,
  width = pdf_width,
  height = pdf_height,
  units = "in",
  dpi = 300,
  device = "png"
)

message("Saved PDF: ", outfile_pdf)
message("Saved PNG: ", outfile_png)